export function downloadReferralNote(result, symptoms) {
  const date = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const content = `
MEDICAL TRIAGE REFERRAL NOTE
Generated: ${date}

PATIENT SYMPTOMS:
${symptoms}

URGENCY ASSESSMENT:
Level: ${result.urgencyLevel} (Score: ${result.urgencyScore}/10)

${result.redFlags && result.redFlags.length > 0 ? `
RED FLAGS IDENTIFIED:
${result.redFlags.map(flag => `• ${flag}`).join('\n')}
` : ''}

RECOMMENDATIONS:
${result.recommendations.map(rec => `• ${rec}`).join('\n')}

${result.emergencyDetected ? `
⚠️ EMERGENCY DETECTED
This patient requires immediate medical attention.
Recommended action: Call 108 or visit nearest emergency department immediately.
` : ''}

DISCLAIMER:
This is an AI-generated triage assessment for informational purposes only.
It is not a substitute for professional medical diagnosis or treatment.
Please consult with a qualified healthcare provider for proper evaluation.

---
Generated by Medical Triage System
  `.trim();

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `medical-triage-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
